[package]
name = "walle-daemon"
version.workspace = true
edition.workspace = true
autobins = false

[lib]
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
rand.workspace = true
russh.workspace = true
similar = "2.7"
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
walle-common = { path = "../walle-common" }
walle-policy = { path = "../walle-policy" }

[target.'cfg(target_os = "linux")'.dependencies]
aya.workspace = true
libc = "0.2"
